controller_manager:
  ros__parameters:
    update_rate: 31
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_trajectory_controller:
  ros__parameters:
    joints:
      - middle_joint
      - arm_joint
      - hand_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
